"""Dynamic cutdown-aware length shaping for DenoiseRL v2 rollouts.

For a prefix of length ``p`` and generation budget ``R``, cutdown can keep at
most ``R - p`` generated tokens. Rollouts keep their full reward up to that
boundary. The following ``p`` generated tokens form a per-sample dynamic cache
in which the configured samples receive a linearly increasing penalty.
"""

import math
from typing import Tuple

import torch


def dynamic_cutdown_length_factor(
    response_lengths: torch.Tensor,
    *,
    prefix_lengths: torch.Tensor,
    max_response_length: int,
    min_factor: float = 0.0,
) -> torch.Tensor:
    """Return factors using each row's prefix length as its dynamic cache."""
    if max_response_length <= 0:
        raise ValueError(
            f"max_response_length must be > 0, got {max_response_length}."
        )
    if not math.isfinite(min_factor) or not 0.0 <= min_factor <= 1.0:
        raise ValueError(f"min_factor must be finite and in [0, 1], got {min_factor}.")

    lengths = torch.as_tensor(response_lengths)
    prefixes = torch.as_tensor(prefix_lengths, device=lengths.device)
    if lengths.shape != prefixes.shape:
        raise ValueError(
            "response_lengths and prefix_lengths must have the same shape, "
            f"got {tuple(lengths.shape)} and {tuple(prefixes.shape)}."
        )
    if not torch.is_floating_point(lengths):
        lengths = lengths.to(torch.float32)
    prefixes = prefixes.to(dtype=lengths.dtype)
    if not torch.isfinite(lengths).all():
        raise ValueError("response_lengths must contain only finite values.")
    if not torch.isfinite(prefixes).all():
        raise ValueError("prefix_lengths must contain only finite values.")
    if torch.any(lengths < 0):
        raise ValueError("response_lengths must be non-negative.")
    if torch.any(prefixes < 0) or torch.any(prefixes > max_response_length):
        raise ValueError(
            "prefix_lengths must be in [0, max_response_length]."
        )

    penalty_start = float(max_response_length) - prefixes
    overrun = (lengths - penalty_start).clamp(min=0.0)
    cache_progress = torch.where(
        prefixes > 0,
        overrun / prefixes.clamp(min=1.0),
        torch.zeros_like(overrun),
    ).clamp(max=1.0)
    return 1.0 - (1.0 - min_factor) * cache_progress


def apply_dynamic_length_reward(
    reward_tensor: torch.Tensor,
    *,
    correctness: torch.Tensor,
    response_lengths: torch.Tensor,
    prefix_lengths: torch.Tensor,
    reward_positions: torch.Tensor,
    max_response_length: int,
    min_factor: float = 0.0,
    scope: str = "correct",
) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    """Apply the dynamic cutdown penalty to correct or all rollouts.

    Args:
        reward_tensor: Token-level rewards with batch as the first dimension.
        correctness: One correctness value per rollout; values greater than zero
            are treated as correct.
        response_lengths: Number of tokens generated by the policy before the
            prefix is folded into the response window.
        prefix_lengths: Injected prefix length for each rollout. This is also the
            row's dynamic cache length.
        reward_positions: Response-column index at which to place the sequence-level
            additive penalty for each rollout.
        max_response_length: Policy generation budget.
        min_factor: Factor at ``max_response_length`` for rows with a non-zero
            prefix. Rows without a prefix keep factor ``1.0``.
        scope: ``"correct"`` applies the penalty only when correctness is positive;
            ``"all"`` applies it to every rollout.

    Returns:
        ``(shaped_reward_tensor, effective_factors, effective_penalties)``.
    """
    if reward_tensor.ndim < 1:
        raise ValueError("reward_tensor must have a batch dimension.")
    if reward_tensor.ndim != 2:
        raise ValueError(
            f"reward_tensor must be 2D, got shape {tuple(reward_tensor.shape)}."
        )
    scope = str(scope).lower()
    if scope not in ("correct", "all"):
        raise ValueError(f"scope must be 'correct' or 'all', got {scope!r}.")

    batch_size = reward_tensor.shape[0]
    correctness_t = torch.as_tensor(correctness, device=reward_tensor.device).reshape(-1)
    response_lengths_t = torch.as_tensor(
        response_lengths, device=reward_tensor.device
    ).reshape(-1)
    prefix_lengths_t = torch.as_tensor(
        prefix_lengths, device=reward_tensor.device
    ).reshape(-1)
    reward_positions_t = torch.as_tensor(
        reward_positions, device=reward_tensor.device, dtype=torch.long
    ).reshape(-1)
    if correctness_t.numel() != batch_size:
        raise ValueError(
            "correctness must have one value per reward row: "
            f"got {correctness_t.numel()} for batch size {batch_size}."
        )
    if response_lengths_t.numel() != batch_size:
        raise ValueError(
            "response_lengths must have one value per reward row: "
            f"got {response_lengths_t.numel()} for batch size {batch_size}."
        )
    if prefix_lengths_t.numel() != batch_size:
        raise ValueError(
            "prefix_lengths must have one value per reward row: "
            f"got {prefix_lengths_t.numel()} for batch size {batch_size}."
        )
    if reward_positions_t.numel() != batch_size:
        raise ValueError(
            "reward_positions must have one value per reward row: "
            f"got {reward_positions_t.numel()} for batch size {batch_size}."
        )
    if torch.any(reward_positions_t < 0) or torch.any(
        reward_positions_t >= reward_tensor.shape[1]
    ):
        raise ValueError(
            f"reward_positions must be in [0, {reward_tensor.shape[1] - 1}]."
        )
    if not torch.isfinite(correctness_t.to(torch.float32)).all():
        raise ValueError("correctness must contain only finite values.")

    factors = dynamic_cutdown_length_factor(
        response_lengths_t,
        prefix_lengths=prefix_lengths_t,
        max_response_length=max_response_length,
        min_factor=min_factor,
    ).to(device=reward_tensor.device, dtype=reward_tensor.dtype)
    correct_mask = correctness_t > 0
    apply_mask = (
        torch.ones_like(correct_mask, dtype=torch.bool)
        if scope == "all"
        else correct_mask
    )
    raw_penalties = 1.0 - factors
    effective_penalties = torch.where(
        apply_mask, raw_penalties, torch.zeros_like(raw_penalties)
    )
    effective_factors = 1.0 - effective_penalties

    shaped_reward = reward_tensor.clone()
    row_indices = torch.arange(batch_size, device=reward_tensor.device)
    shaped_reward[row_indices, reward_positions_t] -= effective_penalties
    return shaped_reward, effective_factors, effective_penalties


def apply_response_clip_penalty(
    reward_tensor: torch.Tensor,
    *,
    response_lengths: torch.Tensor,
    reward_positions: torch.Tensor,
    max_response_length: int,
    penalty: float,
) -> Tuple[torch.Tensor, torch.Tensor]:
    """Subtract a fixed reward from rollouts that exhaust the generation budget.

    ``response_lengths`` must describe the policy-generated continuation before
    any DenoiseRL prefix folding. A row is treated as clipped when its generated
    length reaches ``max_response_length``.

    Returns:
        ``(shaped_reward_tensor, clipped_mask)``.
    """
    if reward_tensor.ndim != 2:
        raise ValueError(
            f"reward_tensor must be 2D, got shape {tuple(reward_tensor.shape)}."
        )
    if max_response_length <= 0:
        raise ValueError(
            f"max_response_length must be > 0, got {max_response_length}."
        )
    if not math.isfinite(penalty) or penalty < 0.0:
        raise ValueError(f"penalty must be finite and non-negative, got {penalty}.")

    batch_size = reward_tensor.shape[0]
    response_lengths_t = torch.as_tensor(
        response_lengths, device=reward_tensor.device
    ).reshape(-1)
    reward_positions_t = torch.as_tensor(
        reward_positions, device=reward_tensor.device, dtype=torch.long
    ).reshape(-1)
    if response_lengths_t.numel() != batch_size:
        raise ValueError(
            "response_lengths must have one value per reward row: "
            f"got {response_lengths_t.numel()} for batch size {batch_size}."
        )
    if reward_positions_t.numel() != batch_size:
        raise ValueError(
            "reward_positions must have one value per reward row: "
            f"got {reward_positions_t.numel()} for batch size {batch_size}."
        )
    if not torch.isfinite(response_lengths_t.to(torch.float32)).all():
        raise ValueError("response_lengths must contain only finite values.")
    if torch.any(response_lengths_t < 0):
        raise ValueError("response_lengths must be non-negative.")
    if torch.any(reward_positions_t < 0) or torch.any(
        reward_positions_t >= reward_tensor.shape[1]
    ):
        raise ValueError(
            f"reward_positions must be in [0, {reward_tensor.shape[1] - 1}]."
        )

    clipped_mask = response_lengths_t >= max_response_length
    shaped_reward = reward_tensor.clone()
    row_indices = torch.arange(batch_size, device=reward_tensor.device)
    shaped_reward[row_indices, reward_positions_t] -= (
        clipped_mask.to(reward_tensor.dtype) * penalty
    )
    return shaped_reward, clipped_mask
